"""renamed 'created_at' to 'date_created' and add the following columns to the db latitiude, longitude, tilt_angle, panel_azimuth, total_irradiance

Revision ID: 6c0a8dde52af
Revises: 
Create Date: 2025-10-05 14:12:14.506207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c0a8dde52af'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calculation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_created', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('tilt_angle', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('panel_azimuth', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_irradiance', sa.Float(), nullable=True))
        batch_op.drop_column('create_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calculation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_at', sa.DATETIME(), nullable=True))
        batch_op.drop_column('total_irradiance')
        batch_op.drop_column('panel_azimuth')
        batch_op.drop_column('tilt_angle')
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')
        batch_op.drop_column('date_created')

    # ### end Alembic commands ###
